spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: r1
              uri: lb://CUSTOMER-SERVICE
              predicates:
                Path=/api/customers/**
            - id: r2
              uri: lb://INVENTORY-SERVICE
              predicates:
                Path=/api/products/**

#spring:
#  cloud:
#    gateway:
#      server:
#        webmvc:
#          routes:
#            - id: r1
#              uri: lb://CUSTOMER_SERVICE
#              predicates:
#                - Path=/api/customers/**
#            - id: r2
#              uri: lb://INVENTORY_SERVICE
#              predicates:
#                - Path=/api/products/**
#
#
